### PR TITLE
chore: rename broadcast method

### PR DESCRIPTION
**Pull request by Archento**
experimental -> official

### CODE REVIEW

**Review by jrriehl — COMMENTED** [review]
Should we maintain `experimental_broadcast` as a simple wrapper for `broadcast` so as not to break code that is currently using this? Maybe with a deprecation warning?

**Comment by Archento** [comment]
Although I agree in general with that approach, I would argue that we don't have that much of a user base currently that actively uses broadcast.
If we were to add a stub function acting as a wrapper we need to revisit this topic some time later and remove that function manually. I'm fine either way but the wrapper introduces more work so I'd prefer leaving it out

**Comment by Archento** [comment]
Screenshot 2024-03-06 at 10 46 48

works like a charm

**Review by jrriehl — APPROVED** [review]
LGTM

**Pull request merged**
